//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mikhail__Moschenkov_19
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class ClientsDB : INotifyPropertyChanged
    {
        private decimal _account;
        public long Id { get; set; }
        public short incomes { get; set; }
        public short excomes { get; set; }
        public bool isBanned { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string middleName { get; set; }
        public long pasport { get; set; }
        public decimal account { get { return _account; } set { _account = value; OnPropertyChanged("account"); } }
        public bool isVip { get; set; }
        public bool isLegal { get; set; }
        public long creditID { get; set; }
        public long contributionID { get; set; }

        public event PropertyChangedEventHandler PropertyChanged;
        protected virtual void OnPropertyChanged(string propertyName)
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
        }

        public override string ToString()
        {
            return $"Клиент: {lastName.Trim(' ')} {firstName.Trim(' ')} {middleName.Trim(' ')}, " +
                $"паспорт: {pasport}\nЛицевой счёт: {Id}, баланс: {account}" +
                $"\nVIP: {isVip}, Юр.лицо: {isLegal}\nНомер вклада: {contributionID},Номер займа: {creditID}.";
        }
    }
}
