//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mikhail__Moschenkov_19
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BankSystemEntities : DbContext
    {
        public BankSystemEntities()
            : base("name=BankSystemEntities")
        {
        }
        public BankSystemEntities(string strConnection)
            : base(strConnection)
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            //throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ClientsDB> ClientsDB { get; set; }
        public virtual DbSet<Contribution> Contribution { get; set; }
        public virtual DbSet<Credit> Credit { get; set; }
    }
}
