//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankSystemApp.DataAccess
{
    using BankSystemApp.DataAccess;
    using System;
    using System.Collections.Generic;
    
    public partial class Authorization
    {
        Random rnd = new Random();

        public Role role { get {
                switch (Permission)
                {
                    case 0: return Role.GUEST;
                    case 1: return Role.EMPLOYEE;
                    case 2: return Role.MANAGER;
                    case 3: return Role.ADMINISTRATOR;
                    default: return Role.GUEST;
                }
            } }
        public int Id { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public int Permission { get; set; }
        public string OAuth { get; set; }

        public Authorization()
        {
            OAuth = "";
            for (int i = 0; i < 26; i++)
            {
                OAuth += SymbolsArrey.symbols[rnd.Next(0, SymbolsArrey.symbols.Length)];
            }
        }
    }

    static class SymbolsArrey
    {
        public static char[] symbols = new char[] { 
            '1', '2', '3', '4', '5', '6', '7', '8', '9', '0',
            'Q', 'W', 'E', 'R', 'T', 'Y', 'U', 'I', 'O', 'P',
            'q', 'w', 'e', 'r', 't', 'y', 'u', 'i', 'o', 'p',
            'A', 'S', 'D', 'F', 'G', 'H', 'J', 'K', 'L',
            'a', 's', 'd', 'f', 'g', 'h', 'j', 'k', 'l',
            'Z', 'X', 'C', 'V', 'B', 'N', 'M',
            'z', 'x', 'c', 'v', 'b', 'n', 'm' };
    }

    public enum Role
    {
        GUEST = 0,
        EMPLOYEE = 1,
        MANAGER = 2,
        ADMINISTRATOR = 3
    }
}
