//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankSystem.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contribution
    {
        public long Id { get; set; }
        public Nullable<System.DateTime> dateBegin { get; set; }
        public Nullable<System.DateTime> dateEnd { get; set; }
        public Nullable<System.DateTime> dateLast { get; set; }
        public Nullable<bool> capitalization { get; set; }
        public decimal contribut { get; set; }

        public Contribution()
        {
            dateBegin = DateTime.Now;
            dateLast = DateTime.Now;
        }
    }
}
